apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  selector:
    matchLabels:
      app: app
  replicas: 1
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: arseni/app
          imagePullPolicy: IfNotPresent
          tty: true
          stdin: true
          ports:
            - containerPort: 80
          env:
            - name: spark_db2_url
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.db2.url
            - name: spark_db2_user
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.db2.user
            - name: spark_db2_password
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.db2.password
            - name: spark_db2_table
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.db2.table
            - name: spark_cos_access_key
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.cos.access.key
            - name: spark_cos_secret_key
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.cos.secret.key
            - name: spark_cos_endpoint
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.cos.endpoint
            - name: spark_cos_bucket
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.cos.bucket
            - name: spark_cos_service
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spark.cos.service
